spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
             enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  servlet:
    session:
      timeout: 60m

base:
  url: https://${NGROK_ID}.ngrok-free.app